apiVersion: v1
kind: Service
metadata:
  name: depa-frontend-service
  labels:
    app: depa-frontend
spec:
  type: ClusterIP
  selector:
    app: depa-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

